'use strict';
const path=require('node:path');
const fs=require('node:fs');
const {pathToFileURL}=require('node:url');
const assert=require('node:assert/strict');
(async()=>{
  const root=process.env.SCRIPT2_HB_ROOT;
  const apiFile=['dist/api.js','lib/api.js'].map(file=>path.join(root,file)).find(file=>fs.existsSync(file));
  assert.ok(apiFile,'Installed Homebridge API module was not found.');
  const {HomebridgeAPI}=await import(pathToFileURL(apiFile).href);
  const api=new HomebridgeAPI();let Platform;api.registerPlatform=(plugin,name,ctor)=>{Platform=ctor;};
  require(process.env.SCRIPT2_PACKAGE_ROOT)(api);
  const log=Object.fromEntries(['debug','info','warn','error'].map(level=>[level,()=>{}]));
  const platform=new Platform(log,{platform:'Script2Platform',stateless_switches:[{name:'Smoke trigger',trigger:'unused-command'}]},api);
  api.emit('didFinishLaunching');
  assert.equal(platform.instances.size,1);
  const accessory=[...platform.accessories.values()][0];
  assert.ok(accessory.getService(api.hap.Service.Switch));
  api.emit('shutdown');
  assert.equal([...platform.instances.values()][0].stopped,true);
  console.log('Installed Homebridge API/accessory smoke check passed.');
})().catch(error=>{console.error(error);process.exitCode=1;});
